// <auto-generated />
using AnimalCollectionWithDB.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AnimalCollectionWithDB.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20220105201326_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("AnimalCollectionWithDB.Entities.Animal", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("AnimalTypeID")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("ID");

                    b.HasIndex("AnimalTypeID");

                    b.ToTable("Animals");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            AnimalTypeID = 1,
                            Name = "Chimpanzee"
                        },
                        new
                        {
                            ID = 2,
                            AnimalTypeID = 2,
                            Name = "Bald Eagle"
                        },
                        new
                        {
                            ID = 3,
                            AnimalTypeID = 3,
                            Name = "Green Sea Turtle"
                        },
                        new
                        {
                            ID = 4,
                            AnimalTypeID = 4,
                            Name = "Golden Poisib Frog"
                        },
                        new
                        {
                            ID = 5,
                            AnimalTypeID = 5,
                            Name = "Monarch Butterfly"
                        });
                });

            modelBuilder.Entity("AnimalCollectionWithDB.Entities.AnimalType", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("ID");

                    b.ToTable("AnimalTypes");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Name = "Mammals"
                        },
                        new
                        {
                            ID = 2,
                            Name = "Birds"
                        },
                        new
                        {
                            ID = 3,
                            Name = "Reptiles"
                        },
                        new
                        {
                            ID = 4,
                            Name = "Amphibians"
                        },
                        new
                        {
                            ID = 5,
                            Name = "Invertebrates"
                        });
                });

            modelBuilder.Entity("AnimalCollectionWithDB.Entities.Animal", b =>
                {
                    b.HasOne("AnimalCollectionWithDB.Entities.AnimalType", "AnimalType")
                        .WithMany("Animals")
                        .HasForeignKey("AnimalTypeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AnimalType");
                });

            modelBuilder.Entity("AnimalCollectionWithDB.Entities.AnimalType", b =>
                {
                    b.Navigation("Animals");
                });
#pragma warning restore 612, 618
        }
    }
}
